spring:
  config:
    import: "mail-config-development.yaml"
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: Admin1
    url: jdbc:postgresql://localhost:5432/jwt-auth
    password: JwtAuth123!@#
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true