spring:
  config:
    import: "mail-config-development.yaml"
  cache:
    type: none
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: AdminTest1
    url: jdbc:postgresql://localhost:5433/jwt-auth-testing
    password: JwtAuthTest123!@#
  liquibase:
    drop-first: true
    change-log: classpath:testDB/changelog-master.xml
